on:
  pull_request_target:
    types: [closed]

name: preview-cleanup
run-name: preview-cleanup - PR #${{ github.event.pull_request.number }}

permissions: {}

jobs:
  delete-preview:
    name: delete-preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == true
    steps:
    - name: Delete preview deployment
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deployment delete --project-name=kopernicus-wiki --branch=pr-${{ github.event.pull_request.number }}
